FORMAT: 1A
HOST: https://api.acs-srv.com/bioy/2

# BiOY Version 2

This is the API for the Alpha International Bible In One Year. It allows clients to access and manage commentaries and related resources.

## Authentication

You will need to use an access token when making requests to any non-public endpoint.

# Group Public APIs

Resources related to viewing read only commentaries via the API.  These methods are used by various platforms to access the BiOY.

# BiOY API Root [/public/]

This resource does not have any attributes. Instead it offers the initial public
API affordances in the form of links in the JSON body, following the recommendations of [RCF 5988](https://tools.ietf.org/html/rfc5988).

These are templated links that can be translated to actual URLs programatically by replacing placeholders (in curly brackets)
by corresponding actual values.

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)
    + Attributes
        + commentaries_get_url (string) - URL to get a commentary
        + commentaries_list_url (string) - URL to get a list of commentary teasers
        + commentaries_full_url (string) - URL to get a list of full commentaries

## Get Commentary  [/public/getCommentary/{commentary_id}/{lang}]

Return a single day full commentary object including the bible reading.  

+ Parameters
    + commentary_id (required, number, `1409`) ... ID of the commentary
    + lang (required, string, `zh_HANS`) ... iso language code

### Get Commentary Detail [GET]

+ Response 200 (application/json)
  + Attributes (Commentary)
## List Commentaries [/public/listCommentaries/{lang}/{start_date}/{ret_num}/{page_num}]

Get a list of Commentary teasers for a specified language and start date.

+ Parameters
    + lang (required, string, `es`) ... iso language code
    + start_date (required, date, `2015-06-01`) ... The ISO 8601 date of the day to list commentaries from (e.g. 2015-06-01)
    + page_num (optional, number, `1`) ... The page of commentaries to list
    + ret_num (optional, number, `3`) ... The number of commentaries to list

### List Commentaries [GET]
+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + Include Commentary Teaser

## Batch List Commentaries [/public/listFullCommentariesByBatch/{lang}/{start_date}/{end_date}/{batch}]

Read multiple complete commentary objects in batched between two dates.  A commentary object has the following attributes:

+ Parameters
    + lang (required, string, `es`) ... 2 digit iso language code - defaults to 'en'
    + start_date (required, date, `2015-07-10`) ... The ISO 8601 date of the day to list commentaries from.
    + end_date (required, date, `2015-07-20`) ... The ISO 8601 date of the day to list commentaries to e.g. 2013-02-10
    + batch (required, integer, `5`) - The number of commentaries to return in the batch.

### Batch List Commentary Detail [GET]

+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + Include Commentary

# Group Commentary functions

## Commentary [/commentaries]

Administer the Commentaries held on the Bible in One Year.

+ Attributes (object)
    + cid - Internal system commentary ID.
    + did - The day number.
    + title - The title for the day.
    + introduction - Introduction block in HTML.
    + psalm_proverbs - The commentary for Psalms or Proverbs in HTML format.
    + new_testament - The commentary for New Testament in HTML format.
    + old_testament - The commentary for Old Testament in HTML format.
    + pippa_adds - The HTML text for Pippa Adds.
    + updated - Time the item was last updated in Unix Time format.
    + show_twitter - Display the twitter links (boolean).
    + cartoon_key - URL for cartoon.
    + deleted - Flag defining delete status (boolean)
    + scheduled_for - The mailchimp next scheduled datetime in Unix Time format.
    + day_of_year - The day number.
    + day - object container with Bible content with psalms, proverbs, new testament, old testament readings and text in HTML foramt.
    

### List commentaries [GET]

+ Request

    + Headers

            Authorization: Bearer {access_token}

  
+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + Include Commentary

### Create a commentary [POST]

+ Request

    + Headers

            Authorization: Bearer {access_token}

    + Body

  
+ Response 201 (application/json)

    + Attributes (Commentary)

    
### Read a single commentary [GET /commentaries/{id}]

+ Parameters
    + id (required, integer, `42`) ... Unique ID of the commentary

+ Request

    + Headers

             Authorization: Bearer {access_token}

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + Include Commentary


### Update a Commentary [PUT /commentaries/{id}]

+ Request

    + Headers

            Authorization: Bearer {access_token}

    + Attributes (array)
        + (object)
            + Include Commentary


+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + Include Commentary

### Delete Commentary [DELETE /commentaries/{id}]

+ Parameters
    + id (required, integer, `42`) ... Unique ID of the commentary

+ Request

    + Headers

            Authorization: Bearer {access_token}

+ Response 204


## Day [/days]

Manage day objects.
+ Attributes
  + did (number) - day ID
  + psalm - Psalms verse numbers
  + proverbs - Proverbs verse numbers
  + new_testament - New Testament verse numbers
  + old_testament - Old Testament verse numbers
  + psalm_text - Psalms text in HTML format
  + proverbs_text - Proverbs text in HTML format
  + new_testament_text - New Testament text in HTML format
  + old_testament_text - Old Testament text in HTML format
  + language

### Create Day [POST]
+ Request (application/json)

    + Headers

            Authorization: Bearer {access_token}

    + Attributes (Day)

        
+ Response 201

### List Days [GET]
+ Response 200

### Get Day [GET /days/{id}]
+ Response 200
    + Attributes (Day)

### Update Day [PUT /days/{id}]
+ Request
    + Headers

            Authorization: Bearer {access_token}

    + Attributes (Day)

+ Response 200

### Delete Day [DELETE /days/{id}]
+ Response 204
            
# Group Audio

Manage the Audio stream and ACS components

## Audio [/audio]

+ Attributes
    + id
    + name
    + filename
    + path
    + owner
    + deleted
    + created
    + updated

### List Audio [GET /audio{?limit,page,orderBy,orderType,published}]
+ Parameters
    + limit: `10` (number, optional) - The number of results to return per page.
        + Default: `10`
    + page: `2` (number, optional) - The page of results to return.
        + Default: `1`
    + orderBy: `d.name` (string, optional) - The value for sort results.
        + Default: `d.did`
    + orderType: `ASC` (string, optional) - The value for sort order (Ascending or Descending).
        + Default: `ASC`
    + published: `0` (string, optional) - The value to filter published and unpublished Audio.

+ Request

    + Headers

             Authorization: Bearer {access_token}

+ Response 200 (application/json)

    + Headers

            Accept: application/json

    + Attributes (object)
        + body (array)
            + (Audio)
        + Include Pager


## Approve and Publish [/audio/{id}]
Approve and Publish audio that have been allocated for a daily commentary.

### Approve and Publish Audio [PUT]

+ Parameters
    + id: `23` (number, required) - The Audio Id.

+ Request (application/json)
    
    + Headers
            
            Authorization: Bearer {access_token}    

    + Attributes (object)
        + status: approved (string)
        + published: true (boolean)

+ Response 200 (application/json)

    + Headers
    
            Accept: application/json
            
    + Attributes (Audio)


## Needs Revision [/audio/{audioId}]
Reject audio that have been allocated for a daily commentary.

### Needs Revision [PUT]

+ Parameters
    + audioId: `23` (number, required) - The Audio Id.

+ Request (application/json)
    
    + Headers
            
            Authorization: Bearer {access_token}    

    + Attributes (object)
        + comment: comments (string) - reasons for rejection
        + email: test@gmail.com (string) - email address
        + status: rejected (string) - rejection status

+ Response 200 (application/json)
    + Attributes (Audio)


# Group Translation

Manage the Daily Commentaries Translations

## Translations [/translations]
Display translations allocated for daily commentaries

+ Attributes
    + default (Commentary)
    + translations (array)
        + (Translation)

### List Translations [GET /translations{?limit,page,orderBy,orderType}]
+ Request
    + Parameters
        + limit: `10` (number, optional) - The number of results to return per page.
            + Default: `10`
        + page: `2` (number, optional) - The page of results to return.
            + Default: `1`
        + orderBy: `d.did` (string, optional) - The value to sort results.
            + Default: `d.did`
        + orderType: `ASC` (string, optional) - The value to sort order (Ascending or Descending).
            + Default: `ASC`

    + Headers

             Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Attributes (Translations)


### Create Translation [POST]
Create translation for daily commentary.

+ Request (application/json)

    + Headers

             Authorization: Bearer {access_token}
             
    + Attributes (object)
        + cid: 1234 (number, required) - commentary ID
        + locale: fr (string, required) - locale for this translation
        + Include CommentaryTranslations

+ Response 201 (application/json)

    + Headers

            Accept: application/json

    + Attributes (Translations)

## Update Translation [/{cid}/translations/{translationId}]

Update translation for daily commentary.

### Update Translation [PUT]

+ Parameters
    + cid: 1234 (number, required) - Commentary ID
    + translationId: `1008` (number, required) - The value of translations Id.

+ Request (application/json)

    + Headers

             Authorization: Bearer {access_token}

    + Attributes (CommentaryTranslations)

+ Response 200 (application/json)
    + Attributes (Translations)
    

# Group Users

Manage the user access & groups

## User [/users]
+ Attributes (object)
    + id (number) - the user ID
    + email: example@example.com (string) - email address
    + languages (array)
        

### List Users [GET]

# Group Languages

Manage the Language codes on the system

### Create a Language [POST]

### List Languages [GET]

### Read language [GET]

### Update Language [PUT]

### Delete Language [DELETE]

+ Parameters
    + id (required, integer, `42`) ... Unique ID of the commentary

+ Request

    + Headers

            Authorization: Bearer {access_token}

+ Response 204 (text/html; charset=UTF-8)

    + Headers

            Accept: application/json

# Search

Supports search functions from mobile

# Group Mailchimp

## Submit Campaign

Create a new Mailchimp campaign.  Build and submit the HTML commentary and create a scheduled timewarp campaign.

## List Campaign

List all the processed campaigns with:

- Scheduled date
- Timewarp start date/time based on London Time
- Title of Campaign
- stats - subscribers, opens, clicks for sent campaigns

## Delete Campaign

Remove a Mailchimp campaign.

# Group Dashboard

## Statistics

### Apple

### Android

### Amazon Kindle

### Mailchimp

### YouVersion




# Group Highlights

Resources related to storing and fetching user highlights. **User authentication/filtering not implemented yet**

## Highlights Collection [/highlights{?limit,page}]

Fetch all highlights made by a user

+ Parameters
    + page: `2` (number, optional) - The page of results to return.
        + Default: `1`
    + limit: `25` (number, optional) - The number of results to return per page.
        + Default: `50`

### List all Highlights [GET]

_highlightedLocation_ should be stored as a serialized array in the database

+ Response 200 (application/json)
    + Body
        
            {
                "highlights": [
                    {
                        "id": 1,
                        "commentaryId": 1278,
                        "highlightedFrom": "psalm_proverbs",
                        "highlightedText": "Maecenas sed diam eget risus varius blandit sit amet non magna.",
                        "highlightedLocation: [
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "is accumsan, in rutrum odio sodales. Vestibulum ",
                                "3:5",
                                35,
                                48
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                " primis in faucibus\n                    orci luctus et ultrices posuere cubilia Curae; Sed at tempus mauris.",
                                "3:7",
                                0,
                                108
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "ante ipsum",
                                "3:6:0",
                                0,
                                10
                            ]
                        ],
                        "color": "#FF0000",
                        "created": "2014-10-04T09:33:56+0000"
                    },
                    {
                        "id": 2,
                        "commentaryId": 1228,
                        "highlightedFrom": "commentary",
                        "highlightedText": "Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.",
                        "highlightedLocation: [
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "is accumsan, in rutrum odio sodales. Vestibulum ",
                                "3:5",
                                35,
                                48
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                " primis in faucibus\n                    orci luctus et ultrices posuere cubilia Curae; Sed at tempus mauris.",
                                "3:7",
                                0,
                                108
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "ante ipsum",
                                "3:6:0",
                                0,
                                10
                            ]
                        ],
                        "color": "#CCCCCC",
                        "created": "2014-10-05T09:33:56+0000"
                    },
                    {
                        "id": 2,
                        "commentaryId": 1228,
                        "highlightedFrom": "new_testament",
                        "highlightedText": "Praesent commodo cursus magna, vel scelerisque nisl consectetur et.",
                        "highlightedLocation: [
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "is accumsan, in rutrum odio sodales. Vestibulum ",
                                "3:5",
                                35,
                                48
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                " primis in faucibus\n                    orci luctus et ultrices posuere cubilia Curae; Sed at tempus mauris.",
                                "3:7",
                                0,
                                108
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "ante ipsum",
                                "3:6:0",
                                0,
                                10
                            ]
                        ],
                        "color": "#FF0000",
                        "created": "2014-10-06T09:33:56+0000"
                    }
                ],
                "pager": {
                    "totalItems": 3,
                    "totalPages": 1,
                    "currentPage": 1
                }
            }

+ Response 400 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

### Create a Highlight [POST]

+ commentaryId (number)
+ highlightedFrom (enum[string]) - Options: commentary, psalm_proverbs, new_testament, old_testament
+ highlightedText (string)
+ highlightedLocation (array) - Serialize array when storing in database
+ color (string) - HEX

+ Request (application/json)
    + Body
            
            {
                "commentaryId": 245,
                "highlightedFrom": "old_testament",
                "highlightedText": "Morbi leo risus, porta ac consectetur ac, vestibulum at eros?",
                "highlightedLocation: [
                    [
                        "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                        "is accumsan, in rutrum odio sodales. Vestibulum ",
                        "3:5",
                        35,
                        48
                    ],
                    [
                        "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                        " primis in faucibus\n                    orci luctus et ultrices posuere cubilia Curae; Sed at tempus mauris.",
                        "3:7",
                        0,
                        108
                    ],
                    [
                        "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                        "ante ipsum",
                        "3:6:0",
                        0,
                        10
                    ]
                ],
                "color": "#FF0000"
            }

+ Response 201 (application/json)
    + Body
            
            {
                "highlight": {
                    "id": 234,
                    "commentaryId": 245,
                    "highlightedFrom": "old_testament",
                    "highlightedText": "Morbi leo risus, porta ac consectetur ac, vestibulum at eros?",
                    "highlightedLocation: [
                        [
                            "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                            "is accumsan, in rutrum odio sodales. Vestibulum ",
                            "3:5",
                            35,
                            48
                        ],
                        [
                            "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                            " primis in faucibus\n                    orci luctus et ultrices posuere cubilia Curae; Sed at tempus mauris.",
                            "3:7",
                            0,
                            108
                        ],
                        [
                            "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                            "ante ipsum",
                            "3:6:0",
                            0,
                            10
                        ]
                    ],
                    "color": "#FF0000",
                    "created": "2014-10-06T09:33:56+0000"
                }
            }

+ Response 400 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

## Highlight [/highlights/{id}]

+ Parameters
    + id: `2` (number, required) - The ID of the highlight to delete.

### Delete a Highlight [DELETE]

+ Request (application/json)

+ Response 204 (application/json)

+ Response 400 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

# Group Notes

Resources related to storing and fetching user notes. **User authentication/filtering not implemented yet**

## Notes Collection [/notes{?limit,page}]

Fetch all notes made by a user

+ Parameters
    + page: `2` (number, optional) - The page of results to return.
        + Default: `1`
    + limit: `25` (number, optional) - The number of results to return per page.
        + Default: `50`

### List all Notes [GET]

+ Response 200 (application/json)
    + Body
        
            {
                "notes": [
                    {
                        "id": 1,
                        "commentaryId": 1278,
                        "highlightedFrom": "psalm_proverbs",
                        "highlightedText": "Maecenas sed diam eget risus varius blandit sit amet non magna.",
                        "highlightedLocation: [
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "is accumsan, in rutrum odio sodales. Vestibulum ",
                                "3:5",
                                35,
                                48
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                " primis in faucibus\n                    orci luctus et ultrices posuere cubilia Curae; Sed at tempus mauris.",
                                "3:7",
                                0,
                                108
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "ante ipsum",
                                "3:6:0",
                                0,
                                10
                            ]
                        ],
                        "note": "Aenean lacinia bibendum nulla sed consectetur. Sed posuere consectetur est at lobortis.\n\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.",
                        "created": "2014-10-04T09:33:56+0000",
                        "updated": "2014-10-04T09:33:56+0000"
                    },
                    {
                        "id": 2,
                        "commentaryId": 1228,
                        "highlightedFrom": "commentary",
                        "highlightedText": "Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.",
                        "highlightedLocation: [
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "is accumsan, in rutrum odio sodales. Vestibulum ",
                                "3:5",
                                35,
                                48
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                " primis in faucibus\n                    orci luctus et ultrices posuere cubilia Curae; Sed at tempus mauris.",
                                "3:7",
                                0,
                                108
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "ante ipsum",
                                "3:6:0",
                                0,
                                10
                            ]
                        ],
                        "note": "Aenean lacinia bibendum nulla sed consectetur. Sed posuere consectetur est at lobortis.\n\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.",
                        "created": "2014-10-04T09:33:56+0000",
                        "updated": "2014-10-04T09:33:56+0000"
                    },
                    {
                        "id": 2,
                        "commentaryId": 1228,
                        "highlightedFrom": "new_testament",
                        "highlightedText": "Praesent commodo cursus magna, vel scelerisque nisl consectetur et.",
                        "highlightedLocation: [
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "is accumsan, in rutrum odio sodales. Vestibulum ",
                                "3:5",
                                35,
                                48
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                " primis in faucibus\n                    orci luctus et ultrices posuere cubilia Curae; Sed at tempus mauris.",
                                "3:7",
                                0,
                                108
                            ],
                            [
                                "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                                "ante ipsum",
                                "3:6:0",
                                0,
                                10
                            ]
                        ],
                        "note": "Aenean lacinia bibendum nulla sed consectetur. Sed posuere consectetur est at lobortis.\n\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.",
                        "created": "2014-10-04T09:33:56+0000",
                        "updated": "2014-10-04T09:33:56+0000"
                    }
                ],
                "pager": {
                    "totalItems": 3,
                    "totalPages": 1,
                    "currentPage": 1
                }
            }

+ Response 400 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

### Create a Note [POST]

+ commentaryId (number)
+ highlightedFrom (enum[string]) - Options: commentary, psalm_proverbs, new_testament, old_testament
+ highlightedText (string)
+ highlightedLocation (array) - Serialize array when storing in database
+ note (string) - Plaintext no HTML

+ Request (application/json)
    + Body
            
            {
                "commentaryId": 245,
                "highlightedFrom": "old_testament",
                "highlightedText": "Morbi leo risus, porta ac consectetur ac, vestibulum at eros?",
                "highlightedLocation: [
                    [
                        "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                        "is accumsan, in rutrum odio sodales. Vestibulum ",
                        "3:5",
                        35,
                        48
                    ],
                    [
                        "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                        " primis in faucibus\n                    orci luctus et ultrices posuere cubilia Curae; Sed at tempus mauris.",
                        "3:7",
                        0,
                        108
                    ],
                    [
                        "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                        "ante ipsum",
                        "3:6:0",
                        0,
                        10
                    ]
                ],
                "note": "Aenean lacinia bibendum nulla sed consectetur. Sed posuere consectetur est at lobortis.\n\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et."
            }

+ Response 201 (application/json)
    + Body
            
            {
                "note": {
                    "id": 2323,
                    "commentaryId": 245,
                    "highlightedFrom": "old_testament",
                    "highlightedText": "Morbi leo risus, porta ac consectetur ac, vestibulum at eros?",
                    "highlightedLocation: [
                        [
                            "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                            "is accumsan, in rutrum odio sodales. Vestibulum ",
                            "3:5",
                            35,
                            48
                        ],
                        [
                            "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                            " primis in faucibus\n                    orci luctus et ultrices posuere cubilia Curae; Sed at tempus mauris.",
                            "3:7",
                            0,
                            108
                        ],
                        [
                            "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                            "ante ipsum",
                            "3:6:0",
                            0,
                            10
                        ]
                    ],
                    "note": "Aenean lacinia bibendum nulla sed consectetur. Sed posuere consectetur est at lobortis.\n\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.",
                    "created": "2014-10-04T09:33:56+0000",
                    "updated": "2014-10-04T09:33:56+0000"
                }
            }

+ Response 400 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

## Note [/notes/{id}]

Unlike highlights notes should be __soft-deletable__

+ Parameters
    + id: `2` (number, required) - The ID of the note.

### Update a Note [PUT]

+ note (string) - Plaintext no HTML

+ Request (application/json)
    + Body
            
            {
                "note": "Aenean lacinia bibendum nulla sed consectetur. Sed posuere consectetur est at lobortis.\n\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et."
            }

+ Response 200 (application/json)
    + Body
            
            {
                "note": {
                    "id": 2323,
                    "commentaryId": 245,
                    "highlightedFrom": "old_testament",
                    "highlightedText": "Morbi leo risus, porta ac consectetur ac, vestibulum at eros?",
                    "highlightedLocation: [
                        [
                            "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                            "is accumsan, in rutrum odio sodales. Vestibulum ",
                            "3:5",
                            35,
                            48
                        ],
                        [
                            "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                            " primis in faucibus\n                    orci luctus et ultrices posuere cubilia Curae; Sed at tempus mauris.",
                            "3:7",
                            0,
                            108
                        ],
                        [
                            "<span class=\"highlighted\" data-timestamp=\"1440150908477\" style=\"background-color: rgb(255, 255, 123);\" data-highlighted=\"true\"></span>",
                            "ante ipsum",
                            "3:6:0",
                            0,
                            10
                        ]
                    ],
                    "note": "Aenean lacinia bibendum nulla sed consectetur. Sed posuere consectetur est at lobortis.\n\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.",
                    "created": "2014-10-04T09:33:56+0000",
                    "updated": "2014-10-06T09:33:56+0000"
                }
            }

+ Response 400 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

### Delete a Note [DELETE]

+ Request (application/json)

+ Response 204 (application/json)

+ Response 400 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

# Group Reading Statuses

Resources related to storing and fetching user's read status. **User authentication/filtering not implemented yet**

## Reading Status Collection [/reading-statuses{?limit,page}]

Fetch all reading statuses of a user

+ Parameters
    + page: `2` (number, optional) - The page of results to return.
        + Default: `1`
    + limit: `25` (number, optional) - The number of results to return per page.
        + Default: `50`

### List all Reading Statuses [GET]

+ Response 200 (application/json)
    + Body
        
            {
                "readingStatuses": [
                    {
                        "id": 1,
                        "commentaryId": 1278,
                        "commentary": true,
                        "psalmProverbs": false,
                        "newTestament": false,
                        "oldTestament": true,
                        "created": "2014-10-04T09:33:56+0000",
                        "updated": "2014-10-04T09:33:56+0000"
                    },
                    {
                        "id": 2,
                        "commentaryId": 1279,
                        "commentary": true,
                        "psalmProverbs": true,
                        "newTestament": true,
                        "oldTestament": false,
                        "created": "2014-10-04T09:33:56+0000",
                        "updated": "2014-10-04T09:33:56+0000"
                    },
                    {
                        "id": 3,
                        "commentaryId": 1280,
                        "commentary": true,
                        "psalmProverbs": false,
                        "newTestament": false,
                        "oldTestament": false,
                        "created": "2014-10-04T09:33:56+0000",
                        "updated": "2014-10-04T09:33:56+0000"
                    },
                ],
                "pager": {
                    "totalItems": 3,
                    "totalPages": 1,
                    "currentPage": 1
                }
            }

+ Response 400 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

### Create a Reading Status [POST]

+ commentaryId (number)
+ commentary (boolean)
+ psalmProverbs (boolean)
+ newTestament (boolean)
+ oldTestament (boolean)

+ Request (application/json)
    + Body
            
            {
                "commentaryId": 1280,
                "commentary": true,
                "psalmProverbs": false,
                "newTestament": false,
                "oldTestament": false
            }

+ Response 201 (application/json)
    + Body
            
            {
                "readingStatus": {
                    "id": 4
                    "commentaryId": 1280,
                    "commentary": true,
                    "psalmProverbs": false,
                    "newTestament": false,
                    "oldTestament": false,
                    "created": "2014-10-04T09:33:56+0000",
                    "updated": "2014-10-04T09:33:56+0000"
                }
            }

+ Response 400 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

## Read Status [/reading-statuses/{commentaryId}]

+ Parameters
    + commentaryId: `2` (number, required) - The ID of the commentary.

### Update a Reading Status [PUT]

+ commentary (boolean)
+ psalmProverbs (boolean)
+ newTestament (boolean)
+ oldTestament (boolean)

+ Request (application/json)
    + Body
            
            {
                "commentary": true,
                "psalmProverbs": false,
                "newTestament": false,
                "oldTestament": false
            }

+ Response 200 (application/json)
    + Body
            
            {
                "readingStatus": {
                    "id": 4
                    "commentaryId": 1280,
                    "commentary": true,
                    "psalmProverbs": false,
                    "newTestament": false,
                    "oldTestament": false,
                    "created": "2014-10-04T09:33:56+0000",
                    "updated": "2014-10-04T09:33:56+0000"
                }
            }

+ Response 400 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

# Data Structures

## Commentary Teaser (object)
    + cid - Internal system commentary ID.
    + did - The day number.
    + title - The title for the day.
    + realday - The real day number.
    + teaser - the short teaser text for each commentary.
    
## Translation (object)
    + id (number) - translation ID
    + locale: en (string) - language locale for which this is valid
    + field: psalms_text (string) - field for which this is a translation
    + content (string) - translated content
    + approved: true (boolean) - approved or not
    
## CommentaryTranslations (object)
    + *psalms_text (Translation) - translation keyed by field name
    + *proverbs_text (Translation) - translation keyed by field name

## Pager (object)
    + totalItems (number) - total number of items
    + totalPages (number) - total number of pages
    + currentPage (number) - current page number
